import {
  cup1,
  cup2,
  cup3,
  cup4,
  f1,
  f2,
  f3,
  f4,
  t1,
  t2,
  t3,
  q1,
  q2,
  q3,
  p1,
  p2,
  p3,
  p4,
  p5,
  p6,
  p7,
  p8,
  program1,
  program2,
  program3,
  program4,
  program5,
  program6,
  program8,
  program9,
  program10,
} from "../imports";

export const galleryList = [
  { image: cup1, category: "5th President Running Shield" },
  { image: cup2, category: "5th President Running Shield" },
  { image: cup3, category: "5th President Running Shield" },
  { image: cup4, category: "5th President Running Shield" },

  { image: t1, category: "Excursion" },
  { image: t2, category: "Excursion" },
  { image: t3, category: "Excursion" },

  { image: q1, category: "Red Cross Nepal Quiz Contest" },
  { image: q2, category: "Red Cross Nepal Quiz Contest" },
  { image: q3, category: "Red Cross Nepal Quiz Contest" },

  { image: program1, category: "34th School Anniversary Day" },
  { image: program2, category: "34th School Anniversary Day" },
  { image: program3, category: "34th School Anniversary Day" },
  { image: program4, category: "34th School Anniversary Day" },
  { image: program5, category: "34th School Anniversary Day" },
  { image: program6, category: "34th School Anniversary Day" },
  { image: program8, category: "34th School Anniversary Day" },
  { image: program9, category: "34th School Anniversary Day" },
  { image: program10, category: "34th School Anniversary Day" },

  { image: f1, category: "Farewell Program" },
  { image: f2, category: "Farewell Program" },
  { image: f3, category: "Farewell Program" },
  { image: f4, category: "Farewell Program" },

  { image: p1, category: "Plantation Program" },
  { image: p2, category: "Plantation Program" },
  { image: p3, category: "Plantation Program" },
  { image: p4, category: "Plantation Program" },
  { image: p5, category: "Plantation Program" },
  { image: p6, category: "Plantation Program" },
  { image: p7, category: "Plantation Program" },
  { image: p8, category: "Plantation Program" },
];
